"""create patients and referrals tables

Revision ID: 1ba812ca8048
Revises: 
Create Date: 2026-01-31 13:10:14.367013
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '1ba812ca8048'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('is_high_risk', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_CONFIRMATION', 'SCHEDULED', 'ATTENDED', 'RESOLVED', 'MISSED', name='referralstatus'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('referred_to', sa.String(length=255), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_ticket_id'), 'referrals', ['ticket_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referrals_ticket_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_table('patients')
    sa.Enum(name='referralstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
